# Generated by Django 4.1.2 on 2022-10-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'Abierto'), ('2', 'Cerrado')], default='1', max_length=32),
        ),
    ]
