# Generated by Django 4.1.2 on 2022-10-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Category:'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=255),
        ),
    ]
