# Generated by Django 4.1.2 on 2022-11-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0004_alter_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
