# Generated by Django 4.1.2 on 2022-11-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0005_post_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
