# Generated by Django 4.1.2 on 2022-12-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0006_post_latitude_post_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default='20'),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default='20'),
        ),
    ]
